---

- name: make sure an image and script are provided
  fail:
    msg:
        "In order to use this role image_to_modify and modify_script must be
         provided."
  when: image_to_modify is not defined or (modify_script is not defined and modify_image_upload_files == [])

- include: libguestfs.yml
  when: libguestfs_mode|bool

- include: manual.yml
  when: not libguestfs_mode|bool
